//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class CSFuncTestWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(CSFuncTest), typeof(System.Object));
		L.RegFunction("CSFunc", CSFunc);
		L.RegFunction("New", _CreateCSFuncTest);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateCSFuncTest(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				CSFuncTest obj = new CSFuncTest();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: CSFuncTest.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CSFunc(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			CSFuncTest.CSFunc();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

